navbarPage("Haushaltsbuch",
  tabPanel("Verwaltung",
           tabsetPanel(
              tabPanel("Kontenverwaltung",
                       p("0")
                       ),
              tabPanel("Kontoauszüge importieren",
                       p("1")
                       ),
              tabPanel("Datenstand anzeigen",
                       p("2")
                       ),
              tabPanel("Kategorienverwaltung",
                       p("3")
                       )
           )
  ),
  tabPanel("Ausgabenverwaltung",
          p("Ausgabenverwaltung")
  ),
  tabPanel("Einnahmenverwaltung",
          p("Einnahmenverwaltung")
  ),
  tabPanel("Kontoübersicht",
          p("Kontoübersicht")
  ),
  tabPanel("Kontoverlauf",
          p("Kontoverlauf")
  ),
  tabPanel("Kontoanalyse",
          p("Kontoanalyse")
  )
)
